// Generated by nte-dumper; do not hand-edit.
pub const GET_SERVERLIST_URL: usize = 0x8214DE0;
pub const FCURL_HTTP_REQUEST_SET_URL: usize = 0x1D39D10;
pub const UHTUI_LOGIN_SETUP_CALLBACKS: usize = 0x8BECA51;
pub const LOCAL_LOGIN_ENTRY: usize = 0x8C0A600;
pub const LOCAL_LOGIN_SUBMIT: usize = 0x8C09CF0;
pub const FSTRING_ASSIGN: usize = 0x14A0C20;
pub const FMEMORY_FREE: usize = 0x14E9500;
pub const EDITABLE_TEXT_GET_TEXT: usize = 0x3BF4690;
pub const TEXT_TO_STRING: usize = 0x43A5800;
pub const LOGIN_ACCOUNT: usize = 0xFC0;
pub const LOGIN_SERVER_ADDRESS: usize = 0x10E8;
pub const LOGIN_ACCOUNT_PANEL: usize = 0xFF0;
pub const LOGIN_SHOW_PANEL: usize = 0x550;
